#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
cat << EOF
In the corner is a decaying old altar of some forgotten god.

There is a small trinket on the ground.  It looks religious
in nature.

EOF
printf "Do you want to put the trinket back on the altar? y/n  "
read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
    cat << EOF
You place the trinket upon the altar.  You feel a gentle
breeze pass through the room.

EOF
    touch .bless
else
    printf "Do you want to take the trinket for yourself? y/n  "
    read RESP
    if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
        echo "Remember to add the trinket to your inventory!"
        touch .curse
    else
        cat << EOF
You leave the trinket where it lies.  There is a great
sadness here.  You feel compelled to move on.

EOF

        touch .curse
   fi
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./altar
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 


