#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
if [[ -e potion ]]; then
    cat << EOF
You have summoned a potion from afar.  You drink it quickly
and feel a surge of strength.

Add 5 HP to your score.

EOF
else
    cat << EOF
A page from a druid's tome of incantations lies on the
ground.  It reveals to you how to summon a healing potion:

# To find a file on your system, use the find command.  For
# example, to search this room: 

find . -name "potion"

# Once you've found a potion, copy it to this directory and
# run this spell script again.

There are no potions in this room.  But try searching
starting at the entrance.

Hint: use pwd to determine how many rooms (folders) are
between you and the entrance.

EOF

fi


















































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./spell

