#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
# 
if [ -e drum ]; then
    cat << EOF
War drums pound in the distance, giving Nyarlathotep
strength. 

If you know a spell to un-summon the drums, Nyarlathotep
would probably weaken!  Look up the "mv" or "rm" command.

EOF
else
    cat << EOF
The drumming has stopped.  Now is your chance to attack!

EOF
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./drummer
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 

